# 0. Misc
matrix:
  include:
    - name: "Node.js 8.10"
      language: node_js
      node_js: "8.10"
      env: CACHE_NAME=node-8.10

    - name: "Node.js latest"
      language: node_js
      node_js: node
      env: CACHE_NAME=node

# 1. Notifications
notifications:
  slack:
    rooms:
      # atex-ci
      - secure: "JGrzGV5aXIvP6HTjlfylQW/np3bozv28T7pS9M55EJIqUCAfyyzz8dBW34wIooSWhSJXMlngpzCp6at+4dTGsLQJ1YNfG16Koubv4KH//Wg5TwwIEN4J1vy+2r9Kp4+/RGNL0xz4wVnaZ4pRfJQcjWdEVSXGDfNmI3vBa1zPqlqfJS5Em8RF5CeG48wTUrxO/hPCEo18M7LnS6LaMNBSt2+FHkzP7qRh87thdsSGATGaA6CSEnIcjhEO5WtESGrMe3Hu9Ze96WL0d3ry8Ez6Xlh+/nV98ZgQ9hRuKV8Z+Sqc4LhmbjKNWXxjeW1y+NEIb6F0i7adUzFV4RkrqHhoiobX1xRLhTOgBme3q0cuaumXgToV0H8BKNVpL4P40VIaBkLKAE6s4nrHLJV0Gkh3o8+bdxbnLoL6CkLPHFGr1wXJ7n8WOFNEpAViRdrhckeLCxy7IWYDQiMIh6hYckyoqXv1IBCVnHz5Av7YZ9NEYvMJlTSGKvZzg95o3q39Htrvpl6dymROcnX3ac7C6ePAsYXw2r520cbiKy+xFUqSiKUr4l0sqK/BFY7H7Q/ZCvwHIODw0Do1zlctVNCaOZFE4HTQAnq6jfC0hFZUBZd6wdFI29/lBmPspLviBxCe7az9bzB0lwj+gIjyTHSsTG7gZehCbF49jbUG7zZGQ9oC2kc="
      # cloud-ci
      - secure: "S9pt4tCiC4P9vDwpeNhFrNnL8LghYw3isBC9G4AxTfE21teN/IZzDrVu5oUSl55xjuA38jHyW8SczIyjhUPRmquS2O/w0KqjnTX/BFfvtQdeIbAw5U9IFmy9HdQuo37dW1HuDXDMY0etlvwNo34r56BfizmnCVL2/QqwnuxFdeA6BOCLhUvItFc6XZxWGX1Vxm+kQUTqQnzeCynhVtqaqccQbXm53qv57TPKOY39gOZq8bX6x0OMol5gB+n9IQnaK/1U981tu6g+ja66sRy5Ujs5xez25sESf8muOriRWscO9DaCQ4rQntfb1Rbfs0+Phyp+2vby6QdJ8lC3VYikZdINBD3hRHgiidxjMWN8BElChdLHVPOlLeraY8oNJfOpIycnt6V47O02D6QxSHnyOuswbRO7FSknpH6u9CWCg12GPltZO0CE+NKKZ2oaG8umyJktU8eT2J+Sk0QPxxOiEnVjCjzADsT005+Fwfcj2hQFU+NxzCCArfVI90SwFvBGVZBr3rcKq01+NRIjQ2mAOAdDY9VTVPjZ/6j+Ad0IeaUlSKyOe45ldJB4mRLx0A8AF4xHBSfzoNYVIhrS9bA5oDawVH8q8DfcGIX6zzpETFV59G4xKo5X5iWHmWSjI+F1wqX4HUOxd7pA1M29hOZ9OVem4aKJ3QYtCFYwXpTSBdI="
    on_success: change
    on_pull_requests: false

# 2. Env
# env:

# 3. Git
# git:
branches:
  only:
    - master
    - /^v(\d+)\.(\d+)\.(\d+)/ # version tags

# 4. Bootstrap
os: linux
dist: xenial
# addons:
before_cache: ./.ci.sh before_cache
cache:
  directories:
    # common
    - $HOME/.local
    - $HOME/.npm
    # darwin
    - $HOME/.homebrew
    - $HOME/Library/Caches/Homebrew
    - $HOME/Library/Caches/pip
    # linux
    - $HOME/.cache/Homebrew
    - $HOME/.cache/pip
    - $HOME/.linuxbrew

# 5. Steps
before_install: ./.ci.sh before_install
install: ./.ci.sh install
before_script: ./.ci.sh before_script
script: ./.ci.sh script
after_success: ./.ci.sh after_success
after_failure: ./.ci.sh after_failure
after_script: ./.ci.sh after_script

# 6. Deploy
before_deploy: ./.ci.sh before_deploy
# deploy:
after_deploy: ./.ci.sh after_deploy
